# Use a Node.js version that is compatible with your dependencies
FROM node:18

# Create the directory and set it as the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to leverage caching
COPY package*.json ./

# Install dependencies
RUN yarn install --production

# Copy the application source code
COPY . .

# Expose the port your app runs on
EXPOSE 5000

# Command to start your app
CMD ["node", "index.js"]
